# Generated by Django 5.2 on 2025-05-26 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profesores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_evento", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("ubicacion_evento", models.CharField(max_length=100)),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("academico", "Académico"),
                            ("cultural", "Cultural"),
                            ("deportivo", "Deportivo"),
                            ("social", "Social"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "telefono_contacto",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "profesor_encargado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_asociados",
                        to="profesores.profesor",
                    ),
                ),
            ],
        ),
    ]
