# Generated by Django 5.2 on 2025-05-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="telefono_contacto",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
