# Generated by Django 5.2 on 2025-05-26 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("grupos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estrategia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("curso", models.CharField(max_length=20)),
                (
                    "anio_escolar",
                    models.CharField(
                        choices=[
                            ("primero", "Primero"),
                            ("segundo", "Segundo"),
                            ("tercero", "Tercero"),
                            ("cuarto", "Cuarto"),
                        ],
                        max_length=10,
                    ),
                ),
                ("grupo", models.CharField(max_length=20)),
                (
                    "nombre",
                    models.CharField(
                        blank=True, default="Estrategia_{id}", max_length=255
                    ),
                ),
                (
                    "autor",
                    models.CharField(blank=True, default="autor_{id}", max_length=255),
                ),
                (
                    "plan_estudios",
                    models.TextField(blank=True, default="plan_estudios_{id}"),
                ),
                (
                    "obj_general",
                    models.TextField(blank=True, default="objetivo_general_{id}"),
                ),
                (
                    "obj_estrategia",
                    models.TextField(blank=True, default="objetivos_estrategia_{id}"),
                ),
                (
                    "dir_grupo",
                    models.CharField(
                        blank=True, default="direccion_grupo_{id}", max_length=255
                    ),
                ),
                (
                    "caract_grupo",
                    models.TextField(blank=True, default="caracteristicas_grupo_{id}"),
                ),
                (
                    "colect_pedagogico",
                    models.TextField(blank=True, default="colectivo_pedagogico_{id}"),
                ),
                (
                    "dim_curricular",
                    models.TextField(blank=True, default="dimension_curricular_{id}"),
                ),
                (
                    "dim_extensionista",
                    models.TextField(
                        blank=True, default="dimension_extensionista_{id}"
                    ),
                ),
                (
                    "dim_politica",
                    models.TextField(
                        blank=True, default="dimension_politico_ideologica_{id}"
                    ),
                ),
                ("obj_dc", models.TextField(blank=True, default="obj_dc_{id}")),
                ("plan_dc", models.TextField(blank=True, default="plan_dc_{id}")),
                ("obj_de", models.TextField(blank=True, default="obj_de_{id}")),
                ("plan_de", models.TextField(blank=True, default="plan_de_{id}")),
                ("obj_dp", models.TextField(blank=True, default="obj_dp_{id}")),
                ("plan_dp", models.TextField(blank=True, default="plan_dp_{id}")),
                (
                    "evaluacion",
                    models.TextField(blank=True, default="evaluacion_integral_{id}"),
                ),
                (
                    "otros_aspectos",
                    models.TextField(blank=True, default="otros_aspectos_{id}"),
                ),
                (
                    "conclusiones",
                    models.TextField(blank=True, default="conclusiones_{id}"),
                ),
                (
                    "grupo_id",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estrategia",
                        to="grupos.grupo",
                    ),
                ),
            ],
            options={
                "unique_together": {("curso", "grupo")},
            },
        ),
    ]
