# Generated by Django 5.2 on 2025-05-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estrategias", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estrategia",
            name="grupo_id",
        ),
        migrations.AddField(
            model_name="estrategia",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="estrategia",
            name="fecha_modificacion",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
