# Generated by Django 5.2 on 2025-05-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estrategias", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estrategia",
            name="anio_escolar",
            field=models.CharField(
                choices=[
                    ("primero", "Primero"),
                    ("segundo", "Segundo"),
                    ("tercero", "Tercero"),
                    ("cuarto", "Cuarto"),
                ],
                max_length=10,
            ),
        ),
    ]
