# Generated by Django 5.2 on 2025-05-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="cargo",
            new_name="rol",
        ),
    ]
