# Generated by Django 5.2 on 2025-05-26 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profesores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("direccion", models.CharField(max_length=100)),
                ("curso", models.CharField(max_length=20)),
                (
                    "anio_escolar",
                    models.CharField(
                        choices=[
                            ("primero", "Primero"),
                            ("segundo", "Segundo"),
                            ("tercero", "Tercero"),
                            ("cuarto", "Cuarto"),
                        ],
                        max_length=10,
                    ),
                ),
                ("caracterizacion", models.TextField()),
                (
                    "guia",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grupo_asignado",
                        to="profesores.profesor",
                    ),
                ),
                (
                    "profesores",
                    models.ManyToManyField(
                        blank=True, related_name="grupos", to="profesores.profesor"
                    ),
                ),
            ],
        ),
    ]
