# Generated by Django 5.2 on 2025-05-26 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estrategias", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grupo", models.CharField(blank=True, max_length=10, null=True)),
                ("codigo", models.CharField(blank=True, max_length=10, null=True)),
                ("periodo", models.CharField(blank=True, max_length=10, null=True)),
                ("fecha", models.DateField(blank=True, null=True)),
                ("autor", models.CharField(blank=True, max_length=50, null=True)),
                ("institucion", models.CharField(blank=True, max_length=50, null=True)),
                ("resumen", models.TextField(blank=True, null=True)),
                ("objetivos", models.TextField(blank=True, null=True)),
                ("actividades", models.TextField(blank=True, null=True)),
                ("resultados", models.TextField(blank=True, null=True)),
                ("analisis", models.TextField(blank=True, null=True)),
                ("desafios", models.TextField(blank=True, null=True)),
                ("proximos_pasos", models.TextField(blank=True, null=True)),
                (
                    "anexos",
                    models.FileField(blank=True, null=True, upload_to="anexos/"),
                ),
                (
                    "estrategia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes",
                        to="estrategias.estrategia",
                    ),
                ),
            ],
        ),
    ]
