# Generated by Django 5.2 on 2025-05-26 20:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("grupos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "periodo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("primer_semestre", "Primer Semestre"),
                            ("segundo_semestre", "Segundo Semestre"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        blank=True, default=datetime.date.today, null=True
                    ),
                ),
                ("autor", models.CharField(blank=True, max_length=50, null=True)),
                ("institucion", models.CharField(blank=True, max_length=50, null=True)),
                ("resumen", models.TextField(blank=True, null=True)),
                ("objetivos", models.TextField(blank=True, null=True)),
                ("actividades", models.TextField(blank=True, null=True)),
                ("resultados", models.TextField(blank=True, null=True)),
                ("analisis", models.TextField(blank=True, null=True)),
                ("desafios", models.TextField(blank=True, null=True)),
                ("proximos_pasos", models.TextField(blank=True, null=True)),
                (
                    "anexos",
                    models.FileField(
                        blank=True, null=True, upload_to="anexos_reportes/"
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes",
                        to="grupos.grupo",
                    ),
                ),
            ],
        ),
    ]
