# Generated by Django 5.2 on 2025-05-26 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grupos", "0001_initial"),
        ("reportes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reporte",
            name="estrategia",
        ),
        migrations.AlterField(
            model_name="reporte",
            name="grupo",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reportes",
                to="grupos.grupo",
            ),
            preserve_default=False,
        ),
    ]
