# Generated by Django 5.2 on 2025-05-26 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0002_remove_reporte_estrategia_alter_reporte_grupo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporte",
            name="anexos",
            field=models.FileField(blank=True, null=True, upload_to="anexos_reportes/"),
        ),
        migrations.AlterField(
            model_name="reporte",
            name="codigo",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="reporte",
            name="fecha",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name="reporte",
            name="periodo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("primer_semestre", "Primer Semestre"),
                    ("segundo_semestre", "Segundo Semestre"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
