# Generated by Django 5.1.6 on 2025-03-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta1', models.CharField(choices=[('muy-bien', 'Muy bien'), ('bien', 'Bien'), ('normal', 'Normal'), ('mal', 'Mal'), ('pesimo', 'Pésimo')], max_length=20)),
                ('pregunta2', models.CharField(choices=[('muy-bien', 'Muy bien'), ('bien', 'Bien'), ('normal', 'Normal'), ('mal', 'Mal'), ('pesimo', 'Pésimo')], max_length=20)),
                ('pregunta3', models.CharField(choices=[('muy-bien', 'Muy bien'), ('bien', 'Bien'), ('normal', 'Normal'), ('mal', 'Mal'), ('pesimo', 'Pésimo')], max_length=20)),
                ('pregunta4', models.CharField(choices=[('muy-bien', 'Muy bien'), ('bien', 'Bien'), ('normal', 'Normal'), ('mal', 'Mal'), ('pesimo', 'Pésimo')], max_length=20)),
                ('pregunta5', models.CharField(choices=[('muy-bien', 'Muy bien'), ('bien', 'Bien'), ('normal', 'Normal'), ('mal', 'Mal'), ('pesimo', 'Pésimo')], max_length=20)),
                ('pregunta6', models.CharField(choices=[('muy-bien', 'Muy bien'), ('bien', 'Bien'), ('normal', 'Normal'), ('mal', 'Mal'), ('pesimo', 'Pésimo')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evento', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('ubicacion_evento', models.CharField(max_length=100)),
                ('tipo_evento', models.CharField(choices=[('academico', 'Académico'), ('cultural', 'Cultural'), ('deportivo', 'Deportivo'), ('social', 'Social')], max_length=20)),
                ('descripcion_evento', models.TextField()),
                ('profesor_cargo', models.CharField(max_length=50)),
                ('telefono_contacto', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=10)),
                ('categoria_docente', models.CharField(choices=[('instructor', 'Instructor'), ('asistente', 'Asistente'), ('auxiliar', 'Auxiliar'), ('titular', 'Titular')], max_length=10)),
                ('asignatura', models.CharField(max_length=50)),
                ('solapin', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=50)),
                ('brigada_asignada', models.CharField(max_length=10)),
                ('brigadas_impartir', models.TextField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=10)),
                ('grupo', models.CharField(max_length=50)),
                ('solapin', models.CharField(max_length=10)),
                ('cargo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=50)),
                ('user', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brigada', models.CharField(max_length=10)),
                ('codigo', models.CharField(max_length=10)),
                ('periodo', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('autor', models.CharField(max_length=50)),
                ('institucion', models.CharField(max_length=50)),
                ('resumen', models.TextField()),
                ('objetivos', models.TextField()),
                ('actividades', models.TextField()),
                ('resultados', models.TextField()),
                ('analisis', models.TextField()),
                ('desafios', models.TextField()),
                ('proximos_pasos', models.TextField()),
                ('anexos', models.FileField(blank=True, null=True, upload_to='anexos/')),
            ],
        ),
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=20)),
                ('anio_escolar', models.CharField(max_length=10)),
                ('grupo', models.CharField(max_length=20)),
                ('nombre', models.CharField(blank=True, default='Estrategia_{id}', max_length=255)),
                ('plan_estudios', models.TextField(blank=True, default='plan_estudios_{id}')),
                ('obj_estrategia', models.TextField(blank=True, default='objetivos_estrategia_{id}')),
                ('dir_brigada', models.CharField(blank=True, default='direccion_brigada_{id}', max_length=255)),
                ('caract_brigada', models.TextField(blank=True, default='caracteristicas_brigada_{id}')),
                ('colect_pedagogico', models.TextField(blank=True, default='colectivo_pedagogico_{id}')),
                ('otros_aspectos', models.TextField(blank=True, default='otros_aspectos_{id}')),
                ('dim_curricular', models.TextField(blank=True, default='dimension_curricular_{id}')),
                ('dim_extensionista', models.TextField(blank=True, default='dimension_extensionista_{id}')),
                ('dim_politica', models.TextField(blank=True, default='dimension_politico_ideologica_{id}')),
                ('conclusiones', models.TextField(blank=True, default='conclusiones_{id}')),
                ('obj_general', models.TextField(blank=True, default='objetivo_general_{id}')),
                ('obj_dc', models.TextField(blank=True, default='obj_dc_{id}')),
                ('plan_dc', models.TextField(blank=True, default='plan_dc_{id}')),
                ('obj_de', models.TextField(blank=True, default='obj_de_{id}')),
                ('plan_de', models.TextField(blank=True, default='plan_de_{id}')),
                ('obj_dp', models.TextField(blank=True, default='obj_dp_{id}')),
                ('plan_dp', models.TextField(blank=True, default='plan_dp_{id}')),
                ('evaluacion', models.TextField(blank=True, default='evaluacion_integral_{id}')),
                ('autor', models.CharField(blank=True, default='autor_{id}', max_length=255)),
            ],
            options={
                'unique_together': {('curso', 'anio_escolar', 'grupo')},
            },
        ),
    ]
