# Generated by Django 5.2 on 2025-05-02 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='brigada_asignada',
        ),
        migrations.AddField(
            model_name='brigada',
            name='guia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brigada_asignada', to='data_models.profesor'),
        ),
        migrations.AlterField(
            model_name='brigada',
            name='profesores',
            field=models.ManyToManyField(blank=True, related_name='brigadas', to='data_models.profesor'),
        ),
    ]
