# Generated by Django 5.1.7 on 2025-03-27 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='estrategia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='data_models.estrategia'),
            preserve_default=False,
        ),
    ]
