# Generated by Django 5.2 on 2025-05-03 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estrategia',
            name='grupo_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estrategia', to='data_models.grupo'),
        ),
        migrations.AlterField(
            model_name='estrategia',
            name='grupo',
            field=models.CharField(max_length=20),
        ),
    ]
