# Generated by Django 5.1.6 on 2025-04-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0002_evento_estrategia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='estrategia',
        ),
        migrations.AlterField(
            model_name='profesor',
            name='brigadas_impartir',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='categoria_docente',
            field=models.CharField(choices=[('instructor', 'Instructor'), ('asistente', 'Asistente'), ('auxiliar', 'Auxiliar'), ('titular', 'Titular')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='solapin',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
