# Generated by Django 5.2 on 2025-05-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0002_estrategia_grupo_id_alter_estrategia_grupo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estrategia',
            unique_together={('curso', 'grupo')},
        ),
    ]
