# Generated by Django 5.1.6 on 2025-04-01 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0003_remove_evento_estrategia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brigada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('caracterizacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Colectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, max_length=100, null=True)),
                ('brigada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_models.brigada')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_models.profesor')),
            ],
        ),
        migrations.AddField(
            model_name='brigada',
            name='profesores',
            field=models.ManyToManyField(related_name='brigadas', through='data_models.Colectivo', to='data_models.profesor'),
        ),
    ]
