# Generated by Django 5.1.6 on 2025-04-01 01:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0004_brigada_colectivo_brigada_profesores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='pregunta1',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='pregunta2',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='pregunta3',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='pregunta4',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='pregunta5',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='pregunta6',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='descripcion',
            field=models.TextField(default='encuesta generica de evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuesta',
            name='titulo',
            field=models.CharField(default='EncuestaA', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='data_models.encuesta')),
            ],
        ),
    ]
