# Generated by Django 5.2 on 2025-05-17 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0004_respuesta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='encuestas',
            new_name='encuestas_realizadas',
        ),
    ]
