# Generated by Django 5.1.6 on 2025-04-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0005_remove_encuesta_pregunta1_remove_encuesta_pregunta2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='autor',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=10),
        ),
    ]
