# Generated by Django 5.1.6 on 2025-04-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0006_encuesta_autor_encuesta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='actividades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='analisis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='autor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='brigada',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='desafios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='institucion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='objetivos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='periodo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='proximos_pasos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='resultados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
