# Generated by Django 5.1.6 on 2025-04-01 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0007_alter_reporte_actividades_alter_reporte_analisis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='descripcion_evento',
            new_name='descripcion',
        ),
    ]
