# Generated by Django 5.2 on 2025-04-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0008_rename_descripcion_evento_evento_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='brigada',
            name='anio_escolar',
            field=models.CharField(default=-1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brigada',
            name='curso',
            field=models.CharField(default=3, max_length=20),
            preserve_default=False,
        ),
    ]
