# Generated by Django 5.2 on 2025-05-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("primer_apellido", models.CharField(max_length=50)),
                (
                    "segundo_apellido",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[
                            ("masculino", "Masculino"),
                            ("femenino", "Femenino"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "categoria_docente",
                    models.CharField(
                        choices=[
                            ("instructor", "Instructor"),
                            ("asistente", "Asistente"),
                            ("auxiliar", "Auxiliar"),
                            ("titular", "Titular"),
                        ],
                        max_length=20,
                    ),
                ),
                ("asignatura", models.CharField(max_length=50)),
                ("solapin", models.CharField(max_length=10, unique=True)),
                ("telefono", models.CharField(max_length=15)),
                ("correo", models.EmailField(max_length=50)),
                ("descripcion", models.TextField()),
            ],
        ),
    ]
