# Generated by Django 5.2 on 2025-05-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encuestas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="respuesta",
            name="evaluacion",
            field=models.CharField(default="regular", max_length=20),
            preserve_default=False,
        ),
    ]
